### ISSUE TITLE
Winlog Event Names

### ISSUE THREAD

**Issue by Joshua1909** [Neo23x0/sigma#665]
I'm fairly new to this project but trying to understand why some of the rules aren't matching in Kibana. The rule is a Windows Security event of a user being added to local Administrators group.
(https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_user_added_to_local_administrators.yml)

In this, it matches a "GroupName" of "Administrators". From what I can tell, in the winlogbeat config we pair "GroupName" to "winlog.event_data.GroupName"
(https://github.com/Neo23x0/sigma/blob/master/tools/config/winlogbeat.yml)

When I run this search in Kibana, "winlog.event_data.GroupName" is not a field identified as extracted from winlogbeat. And looking at the exported fields from elastic documentation, they don't list it. (https://www.elastic.co/guide/en/beats/winlogbeat/7.6/exported-fields-winlog.html)

If I change the search field name to group.name or winlog.event_data.TargetUserName it seems to match. I feel like I am missing something obvious?

UPDATE:
I've tested with Winlogbeat 7.6.1, Kibana 7.6.1, and Elasticsearch 7.6.1.
In troubleshooting I've also tested with Winlogbeat 7.5.0.

**Comment by Neo23x0** [comment]
I am not the one who can give you an answer to your question, but could you tell us, which versions do you use? (Elastic, Kibana, Winlogbeat)

**Comment by thomaspatzke** [comment]
The Elastic documentation seems to be incomplete here. No reference to (the expected) `winlog.event_data.GroupName` or `group.name`, but [seeking through the source code](https://github.com/elastic/beats/search?p=1&q=%22group.name%22+winlogbeat&unscoped_q=%22group.name%22+winlogbeat) shows references in various locations. The [changelog](https://github.com/elastic/beats/blob/96100df8bec05a23506d7fcf37151b35f913c077/CHANGELOG.asciidoc) and [this issue](https://github.com/elastic/beats/pull/10195) only mention Auditbeat. But it clearly appears in [Winlogbeat dashboards](https://github.com/elastic/beats/blob/d86682450e3635fd07a83d0149cead1f2180472f/x-pack/winlogbeat/module/security/_meta/kibana/7/dashboard/bb858830-f412-11e9-8405-516218e3d268.json#L1608) so I think it was changed silently or simply wasn't noticed by the ECS mapping comtributors (I've build the base automatically).

What does our ECS-master @neu5ron say about this? Was this also introduced to ECS from Beats 7.x?

**Comment by neu5ron** [comment]
@Joshua1909 , are you using the modules enabled in your Winlogbeat config? 
in your winlogbeat config if you have something like this, then you are using the "Modules":
```
  - script:
      when.equals.winlog.channel: Security
      lang: javascript
      id: security
      file: ${path.home}/module/security/config/winlogbeat-security.js
```
if so, going forward - you will want to use the SIGMAC https://github.com/Neo23x0/sigma/blob/master/tools/config/winlogbeat-modules-enabled.yml

either way, I see this rule should actually be `TargetUserName` -- however you can fix this temporarily / instantly by adding the following to which ever SIGMAC you are using

**#TODO:**
- [ ] add GroupName in SIGMAC's
- [ ] add GroupSid in SIGMAC's and all rules
- [ ] looks like @neu5ron needs to update winlogbeat modules, that he had been putting off, since some new additions in 7.6 :) 


yes they did add [`group.name` for this EventID into winlogbeat.. 
](https://github.com/elastic/beats/blob/da7a69758d66c9873b197e7e96be629c236b6150/x-pack/winlogbeat/module/security/config/winlogbeat-security.js#L1462)

also future reference for all, to really figure out what is or is not - in ECS for winlogbeat:
- exported fields  = https://www.elastic.co/guide/en/beats/winlogbeat/master/winlogbeat-module-security.html
- what I always use, lol the raw code = https://github.com/elastic/beats/blob/master/x-pack/winlogbeat/module/security/config/winlogbeat-security.js#L1462

**Comment by Joshua1909** [comment]
Thanks everyone, and for the clarification @neu5ron. I did try with both the modules enabled and without, and I tried both yml files. To be honest I didn't realise that modules enabled was for the winlogbeat script was being used, so I learned something there! :)

Now that I have a bit more confidence it works the way I thought, I can go through and make some checks and maybe updates.

Cheers!

**Comment by neu5ron** [comment]
@Joshua1909 I updated my comment like a hundred times, so double check you have the latest (I hope that is my final modification lol)

that would be incredible if you could assist in any way on the winlogbeat ecs sigmac.  and  by the way, ironically I had been thinking about renaming that file to `winlogbeat-ecs-enabled.yml` or just `ecs-winlogbeat.yml` - I knew it may get overlooked for the people who have ECS module enabled .. and low and behold -- here we are :) :1st_place_medal: lol


but that code I sent will fix it right now for you ---  ultimately that's the same code I will be putting in for the PR
